### ISSUE TITLE
How to simulate a linked account?

### ISSUE THREAD

**Issue by westlakem** [bespoken/virtual-alexa#101]
**Is your feature request related to a problem? Please describe.**
We are trying to unit test a feature that requires account linking.

**Describe the solution you'd like**
A way to simulate an account linked device that is able to hit Amazon's profile APIs (we need to hit their APIs once "account linked"

**Comment by jkelvie** [comment]
If you set the access token on the context, it will emulate a user who has linked their account:
`virtualAlexa.context().setAccessToken(testSuite.accessToken);`

We do not have builtin mocks for the profile API, but you we have them for the Address API - a similar approach using Nock (a great mocking tool) will work for the Profile API:
https://github.com/bespoken/virtual-alexa/blob/master/src/external/AddressAPI.ts#L67

**Comment by westlakem** [comment]
Ok, I was looking for mocks of the profile api.
