### ISSUE TITLE
Howto: use a locally hosted lambda

### ISSUE THREAD

**Issue by anandmukundan** [bespoken/virtual-alexa#102]
Hi

I have a lambda hosted in localstack. How can I use that as the handler for running virtual-alexa? (This is not a JS based lambda, so cannot use the normal handler syntax).

Since it is not really a hosted endpoint, I am unable to use the url property.

**Comment by jkelvie** [comment]
Hi @anandmukundan - you can still use it with Virtual Alexa, assuming you have an API gateway configured as a passthru to your lambda. 

You need to make sure that the localstack server is running, then setup virtual alexa with this property:
```
const alexa = va.VirtualAlexa.Builder()
    .skillURL("http://localhost:4567") // Local stack API gateway
    .interactionModelFile("./models/en-US.json") // Path to interaction model file
    .create();
```

**Comment by anandmukundan** [comment]
Thanks @jkelvie, that is what I suspected, but thanks for the confirmation
