### ISSUE TITLE
Dialog Manager- returns response with missing parameters

### ISSUE THREAD

**Issue by anisa114** [bespoken/virtual-alexa#112]
### Description:

Dialog Manager returns a response with missing attributes. The directives are missing the name attribute under the updatedIntent. This results in an undefined name for the dialog. 

Error Message: No match for dialog name: undefined

### Environment:
- Version: 0.7.2
- OS: MacOS 10.14
- Node version: v10.16.0

### Steps To Reproduce
Steps to reproduce the behaviour:
1. Created a request builder for a specific intent 
``
const response = await alexa
      .request()
      .intent("CheckOffersIntent")
      .slot("SponsorName", "SponsorName", "NONE")
      .dialogState("COMPLETED")
      .send();
    console.log(response);
``
2. In the index.js , the CheckOffersIntent delegates the dialog to another intent based on a specific condition 
``
    if (!userRegion || !(userRegion in storesByRegion)) {
      console.log("hit if");
      return handlerInput.responseBuilder
        .addDelegateDirective("NeedRegionCheckOffersIntent")
        .getResponse();
    } else {
      return handlerInput.responseBuilder
        .addDelegateDirective("HasRegionCheckOffersIntent")
        .getResponse();
    }
  }
``
### Code example
``
"response": {
			"directives": [
				{
					"type": "Dialog.Delegate",
					"updatedIntent": {
						"name": "NeedRegionCheckOffersIntent",
						"slots": {}
					}
				}
			],
			"type": "_DEFAULT_RESPONSE"
		}
``
### Code example

In the actual behaviour, the name attribute is missing. Therefore, the dialog manager is unable to match the dialog name from the interaction model. This results in an undefined dialog name 
``
"response": {
			"directives": [
				{
					"type": "Dialog.Delegate",
					"updatedIntent":  "NeedRegionCheckOffersIntent"
			],
			"type": "_DEFAULT_RESPONSE"
		}
``

**Comment by jkelvie** [comment]
Hi @anisa114 - we agree that dialog directive does not look correct. And in turn, it causes virtual alexa to not respond correctly. However, that response is being generated by your code - so your code is what needs to be fixed. Hope that makes sense!

**Comment by anisa114** [comment]
Hello John,

Thank you your quick response. I really appreciate you taking the time to
read my email and issue. I figured out the problem which was in my code.

Regards,

Anisa

**Comment by jkelvie** [comment]
Glad to hear it!
