### ISSUE TITLE
Setting the Viewport in the context is not supported

### ISSUE THREAD

**Issue by ImperviousPanda** [bespoken/virtual-alexa#114]
**Is your feature request related to a problem? Please describe.**
My skill relies on the attribute handlerInput.requestEnvelope.context.Viewport.shape to determine whether it should return the alexa show (square) display or the alexa dot (round) display.  There is not currently a way to set this in the context object using virtual-alexa.

**Describe the solution you'd like**
A more flexible way to set context items in addition to the current features would be great.  Then as the input may change, I have a way to bridge the gap for the context objects that are not yet added by default in the mock.

**Comment by jperata** [comment]
Hi @ImperviousPanda we have the filters as a way to modify the requests for special scenarios like yours
https://github.com/bespoken/virtual-alexa#using-the-request-filter 

you can modify the request so that one thing your element is added and the test what you need

**Comment by ImperviousPanda** [comment]
Great!  Thank you!
