### ISSUE TITLE
Add dialog support

### ISSUE THREAD

**Issue by jkelvie** [bespoken/virtual-alexa#13]
Add support dialog-based interactions

**Comment by allthepies** [comment]
Hi,  any update on this ?  I'd love to use virtual-alexa as part of my automated testing but lots of my skills use the dialog interface and I can't create useful test cases for intents using a dialog.

**Comment by bokostmu** [comment]
I also wanted to ask for an update on this. I have the same problem as allthepies and make extensive use of the dialog interface. A function to set my own properties for the request would be allready enough for me, so i could set the request.dialogState manually.

**Comment by jperata** [comment]
@bokostmu there is already a function to take the request and a function to modify it. You can use filter function from the virtual Alexa instance to add a function that receives the request and modify it as you need.

**Comment by KidA001** [comment]
@jperata @allthepies is there any documentation or examples on this?

**Comment by bokostmu** [comment]
@KidA001 Look at this Issue: https://github.com/bespoken/virtual-alexa/issues/19 . The example given by jkelvie worked for me for understanding.

**Comment by jkelvie** [comment]
Hi @KidA001 - we were overdue to improve our docs on this - aside from the issue mentioned by @bokostmu (and thanks for providing that), take a look at this: https://github.com/bespoken/virtual-alexa/blob/master/docs/Filters.md

**Comment by jkelvie** [comment]
Hello, we have added support for this as part of virtual alexa. You can read about it here:
https://github.com/bespoken/virtual-alexa/blob/master/docs/Dialog.md
