### ISSUE TITLE
Add utterance to alexa.launch() ?

### ISSUE THREAD

**Issue by MnHung** [bespoken/virtual-alexa#24]
Hi all:
```
const launchResponse = await alexa.launch();
```
can simulate a user say "Alexa, open {invocation-name}"

Is it possible to add utterance support to `launch() `, maybe it is like

```
await alexa.launch("do some work");
``` 
to simulate a user say "Alexa, ask {invocation-name} to do some work" ?

and thank you all, you did a great job.

**Comment by jkelvie** [comment]
Hi @MnHung - just saying alexa.utter("do some work") as a first call to the emulator should do it. Have you tried that? It is equivalent to saying "ask skill to do some work".

**Comment by MnHung** [comment]
Thank you @jkelvie , yes it works.
um... should I close it or something? I am new to github

**Comment by jkelvie** [comment]
Yes, go ahead and close. Thanks!

**Comment by jkelvie** [comment]
Hi @ultradian  - you want to call `alexa.launch` instead of `utter` to get a launch request. See here:
https://github.com/bespoken/giftionary/blob/master/test/index.test.js#L48

Let me know if that works for you! Best, John

**Comment by ultradian** [comment]
Thanks,  John.  That works great.  I didn't go deep enough into the code... Is there a doc page besides https://github.com/bespoken/virtual-alexa/blob/master/README.md?  The info at http://docs.bespoken.io/ only describes bstAlexa.

**Comment by jkelvie** [comment]
Yes, take a look here:
https://bespoken.github.io/virtual-alexa/api/

**Comment by ultradian** [comment]
Thanks for the link.  I'll put it in the Github.  A further question that I don't see documented (but probably isn't worth its own issue)... is there a way to trigger the 'Unhandled' intent?
