### ISSUE TITLE
How could I use modern Alexa Skill Interaction Model Scheme in Virtual Alexa?

### ISSUE THREAD

**Issue by hyzhak** [bespoken/virtual-alexa#44]
According to [How do I use it](https://github.com/bespoken/virtual-alexa#how-do-i-use-it) I should pass 2 separate files: intent scheme and sample utterances. But according to [official docs - Interaction Model Schema (Skill Management API)](https://developer.amazon.com/docs/smapi/interaction-model-schema.html) there is only single scheme file. So how could I use that new scheme of Alexa Skill scheme here?

**Comment by jkelvie** [comment]
We also provide a different method, interactionModelFile. You can pass the new schema format via that. You can see an example here:
https://github.com/bespoken/super-simple-unit-testing/blob/master/test/index-test.js

**Comment by hyzhak** [comment]
@jkelvie and @jperata thanks for the hint! It would be very helpful to have this example in the readme file, because it looks like library obsolete and doesn't support new schema.

Btw you don't need `done` parameter there, because you already have promises, just return it from those tests.

**Comment by jkelvie** [comment]
Good suggestion - I added an example with the interaction model file to our latest PR:
https://github.com/bespoken/virtual-alexa/blob/MockAlexaAPI/README.md

And I'm aware about the done versus promise. But I prefer to explicitly call done.
