### ISSUE TITLE
The summary result shows before finishing all of the tests when trace is enable

### ISSUE THREAD

**Issue by MKen-li** [bespoken/virtual-alexa#77]
Preconditions:
-Build = BST 2.0.7
-Set enable trace to "true" 

Steps:

1. Run the script with bst test command

Expected Result:

The summary result shows at the end of all of the tests

Actual Result:

The summary results shows before finishing all of the test 
![trace enable](https://user-images.githubusercontent.com/39920441/41929617-4bca1f2e-793e-11e8-8603-942c785bbba0.png)

**Comment by jkelvie** [comment]
This is just a limitation of how jest works - if you enable console output, it shows up seemingly at random. I do not believe there is any easy way to resolve this issue (short of fixing Jest, which is not easily done).

**Comment by jkelvie** [comment]
I moved this to the next sprint - I think we should double-check that this is not possible, due to limitations in Jest. But assuming that is the case, this is just one of those items we will have to live with.

I do agree that it is less than optimal, but from my research, very difficult to fix.
