### ISSUE TITLE
Charts on Dashboard issues

### ISSUE THREAD

**Issue by MKen-li** [bespoken/virtual-alexa#78]
Build = dev-70

General:
Main Issue (Source, Validation and Check Stats ):
1.Avg response time always shows 0.00 even when the chart in Check Stats shows data

Small Issues / Enhancements:
1. If the skill is not integrated it shouldn't show the charts empty we should display a message to integrate the skill to see.
2. The chart "Daily Events" on Source page and Validation is misleading the name describes the number of events per day but the charts show avg number of events per hour. Talking to Pier about it he tells me that it is possible to have 168 blocks in that chart, in one hand the image according to pier won't break but I got the feeling that it won't be pretty either we might want to check that chart and if we want to keep it make a maximum amount of blocks allow.

Source Page:
-------------------------------------
1. drop down is showing

Validation Page:
-------------------------------------
1. Numbers show be align (Total events, Unique users, Total errors)
2. "Users" in the label "Unique Users" should be lower case

Check Stats Page:
-------------------------------------
1. Labels for charts titles don't have the same size
2. "Number of events per Intent" and "Daily events" are not align when "Source up time" chart is not enable
3. The charts of the left don't show the same days
4. Obscure replicated issue: in 3 occasions others intents appear in the "Number of events per intent" chart (talk to Juan about it he will do some digging on that)  

Enhancement:
The Space of the "Source up time" chart should be in the bottom right displaying a message to enable monitoring to see the chart.

**Comment by jkelvie** [comment]
@MKen-li - with regard to a the response time showing as 0, that may actually be correct. If the skill does not do any IO, it will return very quickly.

Have you tried adding some code before it returns a response, like this:
```
setTimeout(() => {
     // Return response
}, 100);
```

That will add a 100 millisecond delay to the responses, and so should cause the response time to increase.

**Comment by MKen-li** [comment]
@jkelvie  Yes John yesterday I did the test with Pier and he figure out that the function name was incorrect he is already fixing it

**Comment by AnkRaiza** [comment]
deployed (dev-71) fix:
- main issue avg Response time showing just 0.00
- dropdown is not showing
- numbers are aligned
- users does not have capital letter anymore
- titles on the charts have same font size now
- titles are aligned when there is no source up time

**Comment by MKen-li** [comment]
all important issues were fixed, Also after talking to @robertonotte we decide to remove the delete source button in the Check Stats page.
