### ISSUE TITLE
Ensure additional elements do not appear in generated docs

### ISSUE THREAD

**Issue by jkelvie** [bespoken/virtual-alexa#88]
On our generated docs site, additional elements have crept in:
![screenshot 10](https://user-images.githubusercontent.com/17267/44370517-1f33a100-a4a0-11e8-8146-2f7171647895.png)

Specifically, the AWS and nock elements.

I believe this occurs because those elements members of classes that should be marked private but instead are just left as the default (which is then interpreted as public).

**Comment by MKen-li** [comment]
no qa needed
