### ISSUE TITLE
Dialog slot confirmation, documentation needed

### ISSUE THREAD

**Issue by ErikEklund** [bespoken/virtual-alexa#92]
### Description:
I have issues getting dialog testing with slot confirmation to work. I guess it's just an issue of lacking documentation / examples.

When testing for multiple slots, I can do something like this:
```
    alexa.intend("MyIntent").then((payload) => {
        // Send first slot value
        return alexa.intend("MyIntent", { first_value: "1234"});
    }).then((payload) => {
        // Check for OK response and then send second slot value
        return alexa.intend("MyIntent", { second_value: "hello world"});
    });
   // .. and so on
```

This also works great with IntentConfirmation, ie just setting confirmationStatus = ' CONFIRMED' on the request through a filter and calling the intent again. However, I then added slot confirmation to the skill, which works fine in the Alexa test console (getting the Dialog.ConfirmSlot directive and such), but I can not figure out how to do a proper dialog slot confirmation with virtual-alexa.

The documentation states "However, it is incumbent on the developer to issue directives for ElicitSlot, ConfirmSlot and ConfirmIntent", without any further information. Maybe it's just me not grasping this fully, but I feel the documentation could use an example of this use case.

### Environment:
- Version: 0.6.12
- OS: macOS 10.14
- Node version: 10.8.0

**Comment by ig-perez** [comment]
Hello @ErikEklund , thanks a lot for letting us know and sorry for the inconveniences. I'm going to coordinate with the Technical Team, and we’ll get back to you as soon as possible.

Have a great day!

​Iván Pérez
Customer Success
Bespoken
w: | bespoken.io e: ivan@bespoken.io

**Comment by westlakem** [comment]
I'm also having issues with dialog flow (opened a separate issue)  @ig-perez @jperata do you know if anyone is actively looking at the issues?

**Comment by jkelvie** [comment]
Hi Michael - I added a more in-depth response on this ticket #99

**Comment by jperata** [comment]
@westlakem we are trying to look at many of these issues as we can, but we are a small team and sometimes an issue slips through the cracks when an issue gets tagged with a "Sprint XX" on it, it means it's already in our 2 weeks planning to be addressed.

**Comment by jkelvie** [comment]
Hi @ErikEklund - you can manually set the confirmation status of slots now using our new request builder:
```
const response = await alexa.request()
    .intent("MyIntent")
    .slot("SlotName", "SlotValue", "CONFIRMED")
    .send();
```

I know it has been some time since you reported this issue, but take a look and let me know if that helps.

**Comment by ErikEklund** [comment]
Hi @jkelvie!

I had a look at the new examples added, and this seems to be exactly what I was looking for. Sadly the project I was using this for is shipped and archived now, so it's a bit of a hassle to verify, but from the examples everything I was requesting seems to be there now. I'll mark this issue as closed, and if there would be some issue with the new request builder, I'll open up a ticket when I get the chance to try it again :). Thanks!
